### ISSUE TITLE
多久能完工呢？

### ISSUE THREAD

**Issue by netyilei** [ihipop/taobao-top#2]
因为开放平台几乎已经不批ERP了
所以我和第三方合作。  通过他们的服务器转发。

期待你的SDK，等你正式版出来，我就替换掉现在得淘宝SDK

**Comment by ihipop** [comment]
我已经在生产用1.0 aplha，部分细节和现在的0.x版本不兼容，测试下稳定了会放的，swoole的协程支持完善
