### ISSUE TITLE
手动实例化topclient的方式发送请求，提示解密必须指定安全客户端

### ISSUE THREAD

**Issue by xueshandaxia** [ihipop/taobao-top#3]
错误提示如下：

[0] Exception in TopClient.php line 257
解密必须指定安全客户端
    protected function decryptRequest($response, \ihipop\TaobaoTop\requests\TopRequest $request)
    {
        $fieldsConfig = $request->encryptedFields;
        $session      = $request->getSession();
        if (empty($fieldsConfig)) {
            return $response;
        }

        if (!$this->securityClient) {
            throw new \Exception('解密必须指定安全客户端');
        }

我的代码如下：

use GuzzleHttp\Client;
use ihipop\TaobaoTop\client\TopClient;
use ihipop\TaobaoTop\requests\taobao\GetTradesSold;

        $appKey = 'appkey';
        $appSecret = 'appsecret';
        $httpClient = new Client();
        $topClient = new TopClient($appKey,$appSecret,$httpClient);
        $request = new GetTradesSold();
        $request->setFields([
            'post_fee',
            'receiver_name',
            'receiver_state',
            'receiver_address',
            'receiver_zip',
            'receiver_mobile',
            'receiver_phone',
            'consign_time',
            'received_payment',
            'receiver_country',
            'receiver_town',
            'tid',
            'num',
            'status',
            'title',
            'type',
            'price',//其他字段略
        ])->setType([
            'guarantee_trade',
            'auto_delivery',
            'ec',
            'cod',
            'step',
            'tmall_i18n',
            'nopaid',
        ])->setUseHasNext('true')->setPageSize(3);
        $request->setStartCreated(date('Y-m-d H:i:s', time()-86400))->setEndCreated(date('Y-m-d H:i:s', time()));
        $accessToken = 'accessToken';
        $response = $topClient->execute($request, $accessToken);
        var_dump($response);

看源码，在实例化的时候传入一个$appKey，$appSecret，一个http的客户端，一个logger客户端并没有传入这个安全客户端的地方

**Comment by ihipop** [comment]
这是v0.x设计的时候没有考虑到淘宝应用的复杂性 有些应用是没有开启加密的,我用的应用强制开启了加密，所以必须开启安全秘钥，开启后会自动初始化安全客户端。
你可以手动在Request里面把自动解密关掉 
或者稍后我发布正式版，和v0.x不完全兼容 你可以更新到正式版本

**Comment by ihipop** [comment]
发布了 ，你测试下有没有问题，然后关闭此issue
https://github.com/ihipop/taobao-top#%E5%88%9D%E5%A7%8B%E5%8C%96-top-%E5%AE%A2%E6%88%B7%E7%AB%AF
这个版本我在生产上测试过的 大bug应该没有的，和Swoole结合后可以4C单机轻松处理618高峰期所有订单

后面会陆续更新协程下的使用说明

**Comment by xueshandaxia** [comment]
非常感谢，明天我测试一下

**Comment by ihipop** [comment]
记得更新到新版

**Comment by xueshandaxia** [comment]
好的
