### ISSUE TITLE
guzzle 客户端调用taobao.picture.upload，怎么调用呢？

### ISSUE THREAD

**Issue by yancanchen** [ihipop/taobao-top#4]
guzzle 客户端调用taobao.picture.upload，应该不能使用form_params了吧，求解

**Comment by ihipop** [comment]
目前没有实现这个接口的简便类,如果你不想自己实现,你可以用raw request发送请求 https://github.com/ihipop/taobao-top/blob/84a1e77/README.md#raw-request
看了一下文档,
img参数为file_get_contents读取到的文件二进制内容

![image](https://user-images.githubusercontent.com/423077/136057977-d590bc65-28c6-4b72-bfaf-1681722c451b.png)


```php
$response = $topClient->execute($rawRequest, $accessToken)
```

如果你想操作方便一些自己可以封装一个request简便类出来

**Comment by yancanchen** [comment]
有试过guzzle的multipart来请求吗，我尝试了很久，没有弄出来。通过form_params来传rawRequest吗？需要加入一起签名吗？能弄个例子给我吗？
另外schema有集成进来吗？

**Comment by ihipop** [comment]
> 有试过guzzle的multipart来请求吗，我尝试了很久，没有弄出来。通过form_params来传rawRequest吗？需要加入一起签名吗？能弄个例子给我吗？ 另外schema

你new一个RawTopRequest然后通过set方法设置字段,其中  `img参数为file_get_contents读取到的文件二进制内容` 自己试下
guzzle的你需要自己摸索,因为接口有签名 这些在阿里的官方文档里面说的很清楚

https://open.taobao.com/api.htm?spm=a219a.7386797.0.0.52ee669aXwdPzb&source=search&docId=140&docType=2#requestParams

用RawTopRequest你只需要关心自己的业务字段就行了 也就是文档内的`请求参数` 部分

**Comment by yancanchen** [comment]
可以了。淘宝解析头部的字节和我们理解的不太一样。
 public static function httpClient(array $options = [])
    {
        $stack = HandlerStack::create(new CoroutineHandler());
        $stack->push(Middleware::mapRequest(function(RequestInterface $request) {
            $body = $request->getBody();
            /**
             * @var $body \GuzzleHttp\Psr7\MultipartStream
             */
            $appendSteam = new AppendStream();
            $appendSteam->addStream(Utils::streamFor(preg_replace("/Content-Length: \d+\r\n/", '', $body->stream->getContents())));
            $body->stream = $appendSteam;
            $request->withBody($body);
            return $request;
        }));
        $options['handler'] = $stack;
        return make(ClientFactory::class)->create($options);
    }
